### ISSUE TITLE
建议 修改 building immortalWrt 时 

### ISSUE THREAD

**Issue by Wang-Mer** [wukongdaily/AutoBuildImmortalWrt#25]
```
      - name: Get current date and time
        id: date
        run: echo "current_date=$(date '+%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      - name: Create GitHub Release Info
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: Autobuild-x86-64
          name: "ImmortWrt-[那个版本(24.10 或 23.05.4)]-x86-64-efi ${{ env.current_date }}"
          body_path: ${{ github.workspace }}/info.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
