### ISSUE TITLE
麻烦请教下，如何添加直接编译esxi的版本，这样比较方便？

### ISSUE THREAD

**Issue by hbzmt** [wukongdaily/AutoBuildImmortalWrt#48]
麻烦请教下，如何添加直接编译esxi的版本，这样比较方便？

**Comment by wukongdaily** [comment]
这需要你稍微改一下配置
项目里 x86-64/imm.config 此文件中
`CONFIG_VMDK_IMAGES=n `改成y

而且yml尾部输出文件那边也需要增加一行代码

`${{ github.workspace }}/bin/targets/x86/64/*.vmdk`

```
- name: Upload ImmortWrt as release assets
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: Autobuild-x86-64
          body_path: ${{ github.workspace }}/info.md
          files: |
            ${{ github.workspace }}/bin/targets/x86/64/*.vmdk
            ${{ github.workspace }}/immortalwrt-23.05.4-x86-64-generic-squashfs-combined-efi.img.gz
            ${{ github.workspace }}/immortalwrt-23.05.4-x86-64-generic-squashfs-combined-efi.img.gz.sha256
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
